/* общие элементы: тост, шторка, графики на SVG */
window.UI=(function(){
function toast(t){let el=document.getElementById('toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function ensureSheet(){let b=document.getElementById('back'),s=document.getElementById('sheet');if(!b){b=document.createElement('div');b.id='back';b.className='back';document.body.appendChild(b);b.addEventListener('click',closeSheet)}if(!s){s=document.createElement('div');s.id='sheet';s.className='sheet';document.body.appendChild(s);s.addEventListener('click',ev=>{if(ev.target.closest('[data-close]'))closeSheet()})}return s}
function openSheet(html,onReady){const s=ensureSheet();s.innerHTML='<div class="grab"></div>'+html;document.getElementById('back').classList.add('show');requestAnimationFrame(()=>s.classList.add('show'));if(onReady)onReady(s);return s}
function closeSheet(){const s=document.getElementById('sheet'),b=document.getElementById('back');if(s)s.classList.remove('show');if(b)b.classList.remove('show')}
const G='<defs><linearGradient id="lg" x1="0" x2="1"><stop offset="0" stop-color="#F2652A"/><stop offset="1" stop-color="#F6B343"/></linearGradient><linearGradient id="ag" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#F6B343" stop-opacity=".35"/><stop offset="1" stop-color="#F6B343" stop-opacity="0"/></linearGradient></defs>';
/* линия: series=[{v:[numbers],color,width,area,dash}], labels=[{i,t}], opts={h,yfmt,min,max,dots} */
function line(series,labels,opts){opts=opts||{};const W=320,H=opts.h||150,L=34,Rr=8,T=10,B=22;const all=series.flatMap(s=>s.v.filter(x=>x!=null));let mn=opts.min!=null?opts.min:Math.min(...all),mx=opts.max!=null?opts.max:Math.max(...all);if(mx===mn){mx+=1;mn-=1}const pad=(mx-mn)*0.08;mn-=pad;mx+=pad;const n=Math.max(...series.map(s=>s.v.length));
  const X=i=>L+(W-L-Rr)*(n>1?i/(n-1):0.5),Y=v=>T+(H-T-B)*(1-(v-mn)/(mx-mn));const yf=opts.yfmt||(v=>Math.round(v));
  let g='';for(let k=0;k<=3;k++){const v=mn+(mx-mn)*k/3;g+=`<line x1="${L}" x2="${W-Rr}" y1="${Y(v).toFixed(1)}" y2="${Y(v).toFixed(1)}" stroke="#2E2F3C" stroke-width="1"/><text x="${L-6}" y="${(Y(v)+3.5).toFixed(1)}" fill="#7A7C83" font-size="9" text-anchor="end">${yf(v)}</text>`}
  (labels||[]).forEach(l=>{g+=`<text x="${X(l.i).toFixed(1)}" y="${H-6}" fill="#7A7C83" font-size="9" text-anchor="middle">${l.t}</text>`});
  series.forEach(s=>{const pts=s.v.map((v,i)=>v==null?null:[X(i),Y(v)]).filter(Boolean);if(!pts.length)return;const dd=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');
    if(s.area)g+=`<path d="${dd} L${pts[pts.length-1][0].toFixed(1)} ${(H-B).toFixed(1)} L${pts[0][0].toFixed(1)} ${(H-B).toFixed(1)} Z" fill="url(#ag)"/>`;
    g+=`<path d="${dd}" fill="none" stroke="${s.color||'url(#lg)'}" stroke-width="${s.width||2.5}" stroke-linecap="round" stroke-linejoin="round" ${s.dash?'stroke-dasharray="4 4"':''}/>`;
    if(s.dots)pts.forEach(p=>g+=`<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="3" fill="#0E0F1A" stroke="${s.color||'#F6B343'}" stroke-width="2"/>`);
    if(s.end!==false){const p=pts[pts.length-1];g+=`<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="4.5" fill="#F6B343" stroke="#0E0F1A" stroke-width="2"/>`}});
  return `<svg class="gfx" viewBox="0 0 ${W} ${H}" width="100%" style="display:block;overflow:visible">${G}${g}</svg>`}
/* столбцы: vals=[{v,t,hi}] */
function bars(vals,opts){opts=opts||{};const W=320,H=opts.h||140,L=30,T=12,B=22;const mx=Math.max(...vals.map(x=>x.v),1);const n=vals.length;const bw=Math.min(28,(W-L-8)/n*0.62);const yf=opts.yfmt||(v=>Math.round(v));let g='';
  for(let k=0;k<=2;k++){const v=mx*k/2,y=T+(H-T-B)*(1-v/mx);g+=`<line x1="${L}" x2="${W-6}" y1="${y.toFixed(1)}" y2="${y.toFixed(1)}" stroke="#2E2F3C"/><text x="${L-6}" y="${(y+3.5).toFixed(1)}" fill="#7A7C83" font-size="9" text-anchor="end">${yf(v)}</text>`}
  vals.forEach((x,i)=>{const cx=L+(W-L-8)*((i+0.5)/n),h=(H-T-B)*(x.v/mx),y=H-B-h;g+=`<rect x="${(cx-bw/2).toFixed(1)}" y="${y.toFixed(1)}" width="${bw.toFixed(1)}" height="${h.toFixed(1)}" rx="6" fill="${x.hi?'url(#lg)':'#30313F'}"/>`;if(x.t)g+=`<text x="${cx.toFixed(1)}" y="${H-6}" fill="${x.hi?'#F6B343':'#7A7C83'}" font-size="9" text-anchor="middle">${x.t}</text>`;if(x.top)g+=`<text x="${cx.toFixed(1)}" y="${(y-4).toFixed(1)}" fill="#fff" font-size="9" font-weight="700" text-anchor="middle">${x.top}</text>`});
  return `<svg class="gfx" viewBox="0 0 ${W} ${H}" width="100%" style="display:block">${G}${g}</svg>`}
function ring(pct,size,label,sub){size=size||92;const r=(size-10)/2,c=2*Math.PI*r,p=Math.max(0,Math.min(1,pct));return `<svg class="gfx" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" style="flex:none">${G}<circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="#262633" stroke-width="8"/><circle cx="${size/2}" cy="${size/2}" r="${r}" fill="none" stroke="url(#lg)" stroke-width="8" stroke-linecap="round" stroke-dasharray="${(c*p).toFixed(1)} ${c.toFixed(1)}" transform="rotate(-90 ${size/2} ${size/2})"/><text x="50%" y="${sub?'48%':'52%'}" text-anchor="middle" fill="#fff" font-size="${size>80?18:14}" font-weight="800" font-family="Manrope,Arial">${label}</text>${sub?`<text x="50%" y="66%" text-anchor="middle" fill="#7A7C83" font-size="9" font-family="Manrope,Arial">${sub}</text>`:''}</svg>`}
/* колесо успеваемости: 4 оси */
function wheel(vals,labels,size){size=size||220;const cx=size/2,cy=size/2,r=size/2-28;const ang=i=>-Math.PI/2+i*Math.PI/2;const pt=(i,k)=>[cx+r*k*Math.cos(ang(i)),cy+r*k*Math.sin(ang(i))];let g=G;
  [0.25,0.5,0.75,1].forEach(k=>{g+=`<polygon points="${[0,1,2,3].map(i=>pt(i,k).map(v=>v.toFixed(1)).join(',')).join(' ')}" fill="none" stroke="#2E2F3C"/>`});
  [0,1,2,3].forEach(i=>{const p=pt(i,1);g+=`<line x1="${cx}" y1="${cy}" x2="${p[0].toFixed(1)}" y2="${p[1].toFixed(1)}" stroke="#2E2F3C"/>`});
  g+=`<polygon points="${vals.map((v,i)=>pt(i,Math.max(0.04,v)).map(x=>x.toFixed(1)).join(',')).join(' ')}" fill="rgba(246,179,67,.22)" stroke="url(#lg)" stroke-width="2.5" stroke-linejoin="round"/>`;
  vals.forEach((v,i)=>{const p=pt(i,Math.max(0.04,v));g+=`<circle cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="4" fill="#F6B343" stroke="#0E0F1A" stroke-width="2"/>`;const l=pt(i,1.22);g+=`<text x="${l[0].toFixed(1)}" y="${(l[1]+(i===0?-2:i===2?8:4)).toFixed(1)}" text-anchor="middle" fill="#fff" font-size="11" font-weight="700" font-family="Manrope,Arial">${labels[i]}</text><text x="${l[0].toFixed(1)}" y="${(l[1]+(i===0?10:i===2?20:16)).toFixed(1)}" text-anchor="middle" fill="#F6B343" font-size="11" font-weight="800" font-family="Manrope,Arial">${Math.round(v*100)}%</text>`});
  return `<svg class="gfx" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" style="display:block;margin:0 auto;overflow:visible">${g}</svg>`}
function seg(items,active,attr){return `<div class="seg">${items.map(x=>`<button class="${x.k===active?'on':''}" data-${attr||'seg'}="${x.k}">${x.t}</button>`).join('')}</div>`}
return {toast,openSheet,closeSheet,line,bars,ring,wheel,seg}})();
